### ISSUE TITLE
test

### ISSUE THREAD

**Issue by supershal** [supershal/k8s-influxdb#1]
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: influxdb
  name: influxdb-peer-2a-rc
  namespace: infra
spec:
  replicas: 1
  selector:
    app: influxdb
    type: peer
  template:
    metadata:
      labels:
        app: influxdb
        type: peer
    spec:
      containers:
      - name: influxdb
        image: supershal/influxdb:latest
        env:
        - name: NAMESPACE
          value: infra
        - name: INFLUXDB_POD_SELECTORS
          value: app=influxdb
        - name: INFLUXDB_META_RAFT_PROMOTION_ENABLED
          value: "false"
        - name: INFLUXDB_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: INFLUXDB_META_HTTP_BIND_ADDRESS
          value: "$(INFLUXDB_POD_IP):8091"
        - name: INFLUXDB_META_BIND_ADDRESS
          value: "$(INFLUXDB_POD_IP):8088"
        - name: INFLUXDB_HTTP_BIND_ADDRESS
          value: "$(INFLUXDB_POD_IP):8086"
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        ports:
        - name: http
          containerPort: 8083
        - name: api
          containerPort: 8086
        - name: meta
          containerPort: 8088
        - name: meta-http
          containerPort: 8091
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxclaim1
      nodeSelector:
        zone: "us-west-2a"
```
